# 服务配置
server:
  port: 8088

solon:
  app:
    name: bkbits
  env: dev

# 数据源配置
solon.dataSources:
  db1:
    class: "com.zaxxer.hikari.HikariDataSource"
    jdbcUrl: jdbc:mysql://localhost:3306/bkbits?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: dtzn@2022

easy-query:
  db1:
    database: mysql
    name-conversion: underlined
    delete-throw: true
    print-sql: true

solon.logging.logger:
  "root":
    level: INFO
  "com.zaxxer.hikari":
    level: WARN

# 缓存配置（cache.redis 配置块，由 CacheServiceSupplier 自动构建）
solon.redis:
  driverType: "redis" #驱动类型
  server: "localhost:6379"
  db: 0 #默认为 0，可不配置
#  defSeconds: 30 #默认为 30，可不配置
#  password: ""
#  maxTotal: 200 #默认为 200，可不配
