package com.bkbits.admin.pojo;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.bkbits.dbo.entity.Dict }
 *
 * @author lkq
 * @easy-query-dto schema: request
 */
@Data
public class DictValueVO {
    @ApiModelProperty("字典键")
    private String dictKey;

    @ApiModelProperty("字典名称")
    private String name;

    @ApiModelProperty("排序")
    private Integer sort;

    @ApiModelProperty(value = "字典类型", notes = "S=系统字典,U=用户字典")
    private String type;

    @ApiModelProperty("备注")
    private String remark;

    @ApiModelProperty("创建人")
    private String createBy;

    @ApiModelProperty("创建时间")
    private LocalDateTime createTime;

    @ApiModelProperty("更新人")
    private String updateBy;
    
    @ApiModelProperty("更新时间")
    private LocalDateTime updateTime;
}
