package com.bkbits.admin.pojo;


import com.easy.query.core.annotation.EasyWhereCondition;
import lombok.Data;
import com.easy.query.core.annotation.Column;
import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;
import com.easy.query.core.enums.CascadeTypeEnum;
import com.bkbits.util.CollectionUtil;

import java.time.LocalDateTime;

import com.bkbits.orm.IGenId;

import java.util.List;

import lombok.Data;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.bkbits.orm.ICreateBy;
import com.bkbits.orm.IUpdateBy;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.bkbits.dbo.entity.Permission }
 *
 * @author ${appContext.getAuthor()}
 * @easy-query-dto schema: request
 */
@Data
public class PermissionQueryDTO {


    @ApiModelProperty("主键id")
    @EasyWhereCondition(type = EasyWhereCondition.Condition.EQUAL)
    private String id;

    @ApiModelProperty(value = "父级权限", notes = "为空表示顶级权限")
    @EasyWhereCondition(type = EasyWhereCondition.Condition.EQUAL)
    private String parentId;

    @ApiModelProperty(value = "权限类型", notes = "D=目录,M=菜单,B=按钮")
    @EasyWhereCondition
    private String type;

    @ApiModelProperty(value = "权限", notes = "权限应该用 '.' 作为分隔符")
    @EasyWhereCondition
    private String permission;

    @ApiModelProperty("名称")
    @EasyWhereCondition
    private String name;

    @ApiModelProperty("组件")
    @EasyWhereCondition
    private String component;

    @ApiModelProperty(value = "状态", notes = "E=启用,D=禁用")
    @EasyWhereCondition
    private String status;
}
