<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.bkbits</groupId>
        <artifactId>bkbits-framework</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>bkbits-datasource</artifactId>
    <name>bkbits-datasource</name>
    <description>datasource 配置（由 solon.dataSources 配置块自动构建）</description>

    <dependencies>
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-data</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
        </dependency>
    </dependencies>
</project>
