<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.bkbits</groupId>
        <artifactId>bkbits</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>bkbits-admin</artifactId>
    <name>bkbits-admin</name>
    <description>后台业务模块</description>

    <dependencies>
        <dependency>
            <groupId>com.bkbits</groupId>
            <artifactId>bkbits-dbo</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.bkbits</groupId>
            <artifactId>bkbits-base</artifactId>
            <version>${revision}</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-web</artifactId>
        </dependency>
    </dependencies>
</project>
