<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.bkbits</groupId>
        <artifactId>bkbits-framework</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>bkbits-validation</artifactId>
    <name>bkbits-validation</name>
    <description>验证配置</description>

    <dependencies>
        <dependency>
            <groupId>org.noear</groupId>
            <artifactId>solon-security-validation</artifactId>
        </dependency>

        <dependency>
            <groupId>com.bkbits</groupId>
            <artifactId>bkbits-core</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>
</project>
